INSERT ALL
   INTO PROFILE(ID, ADDITIONAL_PHONE_NUMBER, ADDRESS, DATE_OF_BIRTH, LOGIN, NAME, PASSWORD, PHONE_NUMBER) VALUES (1,'','','','admin','Victor','admin','')
   INTO PROFILE(ID, ADDITIONAL_PHONE_NUMBER, ADDRESS, DATE_OF_BIRTH, LOGIN, NAME, PASSWORD, PHONE_NUMBER) VALUES (2,'','','','Masha','Masha','tester','')
SELECT 1 FROM DUAL;

COMMIT;
