INSERT ALL
   INTO PROFILE(ID, ADDITIONAL_PHONE_NUMBER, ADDRESS, DATE_OF_BIRTH, LOGIN, NAME, PASSWORD, PHONE_NUMBER) VALUES (1,'','','','admin','Victor','admin','')
   INTO PROFILE(ID, ADDITIONAL_PHONE_NUMBER, ADDRESS, DATE_OF_BIRTH, LOGIN, NAME, PASSWORD, PHONE_NUMBER) VALUES (2,'','','','Masha','Masha','tester','')
SELECT 1 FROM DUAL;

INSERT ALL
   INTO CATEGORY(ID, TITLE) VALUES (1, 'Вагонка сосна')
   INTO CATEGORY(ID, TITLE) VALUES(2,'Вагонка липа')
   INTO CATEGORY(ID, TITLE) VALUES (3, 'Печи дровяные')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(1,10,0,2,200,0,'Вагонка сосна',0,0.096,1)
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(2,10,0,2.1,200,0,'Вагонка сосна',0,0.096,1)
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(3,10,0,2.2,200,0,'Вагонка сосна',0,0.096,1)
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(4,10,0,2.3,200,0,'Вагонка сосна',0,0.096,1)
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(5,3,0,0,12000,0,'Кирасир 16',0,0,3)
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(6,3,0,0,9800,0,'Анютка мал',0,0,3)
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(7,3,0,0,15000,0,'Термофор 10',0,0,3)
  INTO PRODUCT(ID, AMOUNT, HEIGHT, LENGTH, PRICE, QUADRATURE, TITLE, WEIGHT, WIDTH, CATEGORY_ID) VALUES(8,3,0,0,11900,0,'Greivari',0,0,3)
SELECT 1 FROM DUAL;

COMMIT;

COMMIT;
